/*
 * MemDBG - ShellUI SPRX embedding (extract to filesystem at daemon startup).
 * Copyright (C) 2026 SeregonWar
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * The SPRX is embedded at build time via xxd -i.  This module writes it
 * to /user/data/memdbg/ so the bootstrapper/elfldr can inject it into
 * SceShellUI without needing a separate deployment step.
 */

#include "shellui_embed.h"

#if defined(PLATFORM_PS5) || defined(PS5) || defined(__PROSPERO__) || defined(SHELLUI_EMBED_HOST_TEST)

/* Generated by the build system from the SPRX binary */
#include "memdbg_shellui_embedded.h"

#ifdef SHELLUI_EMBED_HOST_TEST
/* Host test: provide local stubs instead of linking the full daemon */
#include <fcntl.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define MEMDBG_LOG_INFO  1
#define MEMDBG_LOG_ERROR 3
typedef int memdbg_log_level_t;
__attribute__((format(printf, 2, 3)))
static void memdbg_log_write(memdbg_log_level_t level, const char *fmt, ...) {
  (void)level;
  va_list ap;
  va_start(ap, fmt);
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-nonliteral"
  vfprintf(stderr, fmt, ap);
#pragma GCC diagnostic pop
  fputc('\n', stderr);
  va_end(ap);
}
#else
/* PS5: use real daemon headers */
#include "memdbg/core/memdbg.h"
#include "memdbg/core/memdbg_log.h"
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

#ifdef SHELLUI_EMBED_HOST_TEST
# define SHELLUI_OUTPUT_PATH "/tmp/memdbg_embed_test/memdbg_shellui.sprx"
# define SHELLUI_OUTPUT_DIR  "/tmp/memdbg_embed_test"
#else
# define SHELLUI_OUTPUT_PATH "/user/data/memdbg/memdbg_shellui.sprx"
# define SHELLUI_OUTPUT_DIR  "/user/data/memdbg"
#endif

int shellui_embed_extract(void) {
  const unsigned char *data = memdbg_shellui_sprx;
  const size_t data_len = memdbg_shellui_sprx_len;
  struct stat st;

  /* Create output directory if needed */
  mkdir(SHELLUI_OUTPUT_DIR, 0777);

  /* Skip if the file already exists with the correct size */
  if (stat(SHELLUI_OUTPUT_PATH, &st) == 0 &&
      (size_t)st.st_size == data_len) {
    memdbg_log_write(MEMDBG_LOG_INFO,
                     "shellui: SPRX already up-to-date at %s (%zu bytes)",
                     SHELLUI_OUTPUT_PATH, data_len);
    return 0;
  }

  /* Write the embedded SPRX to the filesystem */
  int fd = open(SHELLUI_OUTPUT_PATH,
                O_WRONLY | O_CREAT | O_TRUNC, 0755);
  if (fd < 0) {
    memdbg_log_write(MEMDBG_LOG_ERROR,
                     "shellui: failed to create %s", SHELLUI_OUTPUT_PATH);
    return -1;
  }

  ssize_t written = write(fd, data, data_len);
  close(fd);

  if (written < 0 || (size_t)written != data_len) {
    memdbg_log_write(MEMDBG_LOG_ERROR,
                     "shellui: failed to write SPRX (%zd/%zu bytes)",
                     written, data_len);
    return -2;
  }

  memdbg_log_write(MEMDBG_LOG_INFO,
                   "shellui: extracted SPRX to %s (%zu bytes)",
                   SHELLUI_OUTPUT_PATH, data_len);
  return 0;
}

#else  /* !PLATFORM_PS5 && !SHELLUI_EMBED_HOST_TEST — host stub */

int shellui_embed_extract(void) { return 0; }

#endif /* PLATFORM_PS5 || SHELLUI_EMBED_HOST_TEST */
