/*
 * memDBG - Syscall name table lookup.
 * Copyright (C) 2026 SeregonWar
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Sorted syscall-number → name tables for supported platforms.
 * Selected at compile time via preprocessor defines.
 */

#include "memdbg/tracer/memdbg_tracer.h"

#include <stddef.h>

/* ------------------------------------------------------------------ */
/*  FreeBSD / console (x86-64) syscall table                          */
/* ------------------------------------------------------------------ */

#if defined(__FreeBSD__) || defined(PLATFORM_PS4) || defined(PLATFORM_PS5) || \
    defined(PS4) || defined(PS5) || defined(__ORBIS__) || defined(__PROSPERO__)

#define SC_ENTRY(n, s) { n, s }

static const struct { int no; const char *name; } sc_table[] = {
  SC_ENTRY(  0, "syscall"),
  SC_ENTRY(  1, "exit"),
  SC_ENTRY(  2, "fork"),
  SC_ENTRY(  3, "read"),
  SC_ENTRY(  4, "write"),
  SC_ENTRY(  5, "open"),
  SC_ENTRY(  6, "close"),
  SC_ENTRY(  7, "wait4"),
  SC_ENTRY(  8, "link"),
  SC_ENTRY(  9, "unlink"),
  SC_ENTRY( 10, "execve"),
  SC_ENTRY( 11, "chdir"),
  SC_ENTRY( 12, "fchdir"),
  SC_ENTRY( 13, "mknod"),
  SC_ENTRY( 14, "chmod"),
  SC_ENTRY( 15, "chown"),
  SC_ENTRY( 16, "break"),
  SC_ENTRY( 17, "getfsstat"),
  SC_ENTRY( 18, "lseek"),
  SC_ENTRY( 19, "getpid"),
  SC_ENTRY( 20, "mount"),
  SC_ENTRY( 21, "unmount"),
  SC_ENTRY( 22, "setuid"),
  SC_ENTRY( 23, "getuid"),
  SC_ENTRY( 24, "geteuid"),
  SC_ENTRY( 25, "ptrace"),
  SC_ENTRY( 26, "recvmsg"),
  SC_ENTRY( 27, "sendmsg"),
  SC_ENTRY( 28, "recvfrom"),
  SC_ENTRY( 29, "accept"),
  SC_ENTRY( 30, "getpeername"),
  SC_ENTRY( 31, "getsockname"),
  SC_ENTRY( 32, "access"),
  SC_ENTRY( 33, "chflags"),
  SC_ENTRY( 34, "fchflags"),
  SC_ENTRY( 35, "sync"),
  SC_ENTRY( 36, "kill"),
  SC_ENTRY( 37, "getppid"),
  SC_ENTRY( 38, "dup"),
  SC_ENTRY( 39, "pipe"),
  SC_ENTRY( 40, "getegid"),
  SC_ENTRY( 41, "sigaction"),
  SC_ENTRY( 42, "getgid"),
  SC_ENTRY( 43, "sigprocmask"),
  SC_ENTRY( 44, "getlogin"),
  SC_ENTRY( 45, "setlogin"),
  SC_ENTRY( 46, "acct"),
  SC_ENTRY( 47, "sigpending"),
  SC_ENTRY( 48, "sigaltstack"),
  SC_ENTRY( 49, "ioctl"),
  SC_ENTRY( 50, "reboot"),
  SC_ENTRY( 51, "revoke"),
  SC_ENTRY( 52, "symlink"),
  SC_ENTRY( 53, "readlink"),
  SC_ENTRY( 54, "execve"),
  SC_ENTRY( 55, "umask"),
  SC_ENTRY( 56, "chroot"),
  SC_ENTRY( 57, "msync"),
  SC_ENTRY( 58, "vfork"),
  SC_ENTRY( 59, "munmap"),
  SC_ENTRY( 60, "mprotect"),
  SC_ENTRY( 61, "madvise"),
  SC_ENTRY( 62, "mincore"),
  SC_ENTRY( 63, "getgroups"),
  SC_ENTRY( 64, "setgroups"),
  SC_ENTRY( 65, "getpgrp"),
  SC_ENTRY( 66, "setpgid"),
  SC_ENTRY( 67, "setitimer"),
  SC_ENTRY( 68, "swapon"),
  SC_ENTRY( 69, "getitimer"),
  SC_ENTRY( 70, "getdtablesize"),
  SC_ENTRY( 71, "dup2"),
  SC_ENTRY( 72, "fcntl"),
  SC_ENTRY( 73, "select"),
  SC_ENTRY( 74, "fsync"),
  SC_ENTRY( 75, "setpriority"),
  SC_ENTRY( 76, "socket"),
  SC_ENTRY( 77, "connect"),
  SC_ENTRY( 78, "getpriority"),
  SC_ENTRY( 79, "bind"),
  SC_ENTRY( 80, "setsockopt"),
  SC_ENTRY( 81, "listen"),
  SC_ENTRY( 82, "sigsuspend"),
  SC_ENTRY( 83, "gettimeofday"),
  SC_ENTRY( 84, "getrusage"),
  SC_ENTRY( 85, "getsockopt"),
  SC_ENTRY( 86, "readv"),
  SC_ENTRY( 87, "writev"),
  SC_ENTRY( 88, "settimeofday"),
  SC_ENTRY( 89, "fchown"),
  SC_ENTRY( 90, "fchmod"),
  SC_ENTRY( 91, "setreuid"),
  SC_ENTRY( 92, "setregid"),
  SC_ENTRY( 93, "rename"),
  SC_ENTRY( 94, "flock"),
  SC_ENTRY( 95, "mkfifo"),
  SC_ENTRY( 96, "sendto"),
  SC_ENTRY( 97, "shutdown"),
  SC_ENTRY( 98, "socketpair"),
  SC_ENTRY( 99, "mkdir"),
  SC_ENTRY(100, "rmdir"),
  SC_ENTRY(101, "utimes"),
  SC_ENTRY(102, "adjtime"),
  SC_ENTRY(103, "setsid"),
  SC_ENTRY(104, "getpgid"),
  SC_ENTRY(105, "setprivexec"),
  SC_ENTRY(106, "pread"),
  SC_ENTRY(107, "pwrite"),
  SC_ENTRY(108, "nfssvc"),
  SC_ENTRY(109, "statfs"),
  SC_ENTRY(110, "fstatfs"),
  SC_ENTRY(111, "unmount"),
  SC_ENTRY(112, "async_daemon"),
  SC_ENTRY(113, "getfh"),
  SC_ENTRY(114, "quotactl"),
  SC_ENTRY(115, "mount"),
  SC_ENTRY(116, "waitid"),
  SC_ENTRY(117, "setgid"),
  SC_ENTRY(118, "setegid"),
  SC_ENTRY(119, "seteuid"),
  SC_ENTRY(120, "sigreturn"),
  SC_ENTRY(121, "fdatasync"),
  SC_ENTRY(122, "stat"),
  SC_ENTRY(123, "fstat"),
  SC_ENTRY(124, "lstat"),
  SC_ENTRY(125, "pathconf"),
  SC_ENTRY(126, "fpathconf"),
  SC_ENTRY(127, "getrlimit"),
  SC_ENTRY(128, "setrlimit"),
  SC_ENTRY(129, "getdirentries"),
  SC_ENTRY(130, "mmap"),
  SC_ENTRY(131, "truncate"),
  SC_ENTRY(132, "ftruncate"),
  SC_ENTRY(133, "sysctl"),
  SC_ENTRY(134, "mlock"),
  SC_ENTRY(135, "munlock"),
  SC_ENTRY(136, "getattrlist"),
  SC_ENTRY(137, "setattrlist"),
  SC_ENTRY(138, "poll"),
  SC_ENTRY(139, "getxattr"),
  SC_ENTRY(140, "fgetxattr"),
  SC_ENTRY(141, "setxattr"),
  SC_ENTRY(142, "fsetxattr"),
  SC_ENTRY(143, "removexattr"),
  SC_ENTRY(144, "fremovexattr"),
  SC_ENTRY(145, "listxattr"),
  SC_ENTRY(146, "flistxattr"),
  SC_ENTRY(147, "fsctl"),
  SC_ENTRY(148, "initgroups"),
  SC_ENTRY(149, "posix_spawn"),
  SC_ENTRY(150, "minherit"),
  SC_ENTRY(151, "shm_open"),
  SC_ENTRY(152, "shm_unlink"),
  SC_ENTRY(153, "sem_open"),
  SC_ENTRY(154, "sem_close"),
  SC_ENTRY(155, "sem_unlink"),
  SC_ENTRY(156, "sem_wait"),
  SC_ENTRY(157, "sem_trywait"),
  SC_ENTRY(158, "sem_post"),
  SC_ENTRY(159, "sysctlbyname"),
  SC_ENTRY(160, "shmget"),
  SC_ENTRY(161, "shmctl"),
  SC_ENTRY(162, "shmat"),
  SC_ENTRY(163, "shmdt"),
  SC_ENTRY(164, "msgget"),
  SC_ENTRY(165, "msgsnd"),
  SC_ENTRY(166, "msgrcv"),
  SC_ENTRY(167, "msgctl"),
  SC_ENTRY(168, "semget"),
  SC_ENTRY(169, "semctl"),
  SC_ENTRY(170, "semop"),
  SC_ENTRY(171, "aio_read"),
  SC_ENTRY(172, "aio_write"),
  SC_ENTRY(173, "lio_listio"),
  SC_ENTRY(174, "aio_error"),
  SC_ENTRY(175, "aio_return"),
  SC_ENTRY(176, "aio_suspend"),
  SC_ENTRY(177, "aio_cancel"),
  SC_ENTRY(178, "aio_fsync"),
  SC_ENTRY(179, "mlockall"),
  SC_ENTRY(180, "munlockall"),
  SC_ENTRY(181, "issetugid"),
  SC_ENTRY(182, "sendfile"),
  SC_ENTRY(183, "kqueue"),
  SC_ENTRY(184, "kevent"),
  SC_ENTRY(185, "lchown"),
  SC_ENTRY(186, "uuidgen"),
  SC_ENTRY(187, "sendfile"),
  SC_ENTRY(188, "mac_syscall"),
  SC_ENTRY(189, "getfsstat64"),
  SC_ENTRY(190, "statfs64"),
  SC_ENTRY(191, "fstatfs64"),
  SC_ENTRY(192, "pselect"),
  SC_ENTRY(193, "clock_gettime"),
  SC_ENTRY(194, "clock_settime"),
  SC_ENTRY(195, "clock_getres"),
  SC_ENTRY(196, "nanosleep"),
  SC_ENTRY(197, "sched_yield"),
  SC_ENTRY(198, "sched_getscheduler"),
  SC_ENTRY(199, "sched_setscheduler"),
  SC_ENTRY(200, "sched_getparam"),
  SC_ENTRY(201, "sched_setparam"),
  SC_ENTRY(202, "sched_get_priority_max"),
  SC_ENTRY(203, "sched_get_priority_min"),
  SC_ENTRY(204, "sched_rr_get_interval"),
  SC_ENTRY(205, "futimens"),
  SC_ENTRY(206, "utimensat"),
  SC_ENTRY(207, "posix_fallocate"),
  SC_ENTRY(208, "posix_fadvise"),
  SC_ENTRY(209, "wait6"),
  SC_ENTRY(210, "cap_enter"),
  SC_ENTRY(211, "cap_getmode"),
  SC_ENTRY(212, "cap_rights_limit"),
  SC_ENTRY(213, "cap_ioctls_limit"),
  SC_ENTRY(214, "cap_ioctls_get"),
  SC_ENTRY(215, "cap_fcntls_limit"),
  SC_ENTRY(216, "cap_fcntls_get"),
  SC_ENTRY(217, "bindat"),
  SC_ENTRY(218, "connectat"),
  SC_ENTRY(219, "chflagsat"),
  SC_ENTRY(220, "accept4"),
  SC_ENTRY(221, "pipe2"),
  SC_ENTRY(222, "aio_mlock"),
  SC_ENTRY(223, "procctl"),
  SC_ENTRY(224, "ppoll"),
  SC_ENTRY(225, "futimens"),
  SC_ENTRY(226, "utimensat"),
  SC_ENTRY(227, "numa_getaffinity"),
  SC_ENTRY(228, "numa_setaffinity"),
  SC_ENTRY(229, "fdatasync"),
  SC_ENTRY(230, "fstat"),
  SC_ENTRY(231, "fstatat"),
  SC_ENTRY(232, "fstatfs"),
  SC_ENTRY(233, "getfsstat"),
  SC_ENTRY(234, "getrandom"),
  SC_ENTRY(235, "explicit_bzero"),
  SC_ENTRY(236, "close_range"),
  SC_ENTRY(237, "copy_file_range"),
  SC_ENTRY(238, "shared_align"),
  SC_ENTRY(239, "socket_close"),
  SC_ENTRY(240, "socket_map"),
  SC_ENTRY(241, "socket_open"),
  SC_ENTRY(242, "socket_bind"),
  SC_ENTRY(243, "socket_listen"),
  SC_ENTRY(244, "socket_connect"),
  SC_ENTRY(245, "socket_accept"),
  SC_ENTRY(246, "socket_send"),
  SC_ENTRY(247, "socket_recv"),
  SC_ENTRY(248, "socket_sendto"),
  SC_ENTRY(249, "socket_recvfrom"),
  SC_ENTRY(250, "socket_setsockopt"),
  SC_ENTRY(251, "socket_getsockopt"),
  SC_ENTRY(252, "socket_shutdown"),
  SC_ENTRY(253, "kevent"),
  SC_ENTRY(254, "kqueue"),
  SC_ENTRY(255, "exit_group"),
  SC_ENTRY(256, "tkill"),
  SC_ENTRY(257, "tgkill"),
  SC_ENTRY(258, "sched_setaffinity"),
  SC_ENTRY(259, "sched_getaffinity"),
  SC_ENTRY(260, "futex"),
  SC_ENTRY(261, "futex_requeue"),
  SC_ENTRY(262, "futex_wait"),
  SC_ENTRY(263, "futex_wake"),
  SC_ENTRY(264, "getcwd"),
  SC_ENTRY(265, "readlinkat"),
  SC_ENTRY(266, "linkat"),
  SC_ENTRY(267, "symlinkat"),
  SC_ENTRY(268, "unlinkat"),
  SC_ENTRY(269, "mkdirat"),
  SC_ENTRY(270, "renameat"),
  SC_ENTRY(271, "fchmodat"),
  SC_ENTRY(272, "fchownat"),
  SC_ENTRY(273, "fstatat"),
  SC_ENTRY(274, "faccessat"),
  SC_ENTRY(275, "openat"),
  SC_ENTRY(276, "readlinkat"),
  SC_ENTRY(277, "utimensat"),
  SC_ENTRY(278, "renameat"),
  SC_ENTRY(279, "posix_spawn"),
  SC_ENTRY(280, "recvmsg"),
  SC_ENTRY(281, "sendmsg"),
  SC_ENTRY(282, "recvfrom"),
  SC_ENTRY(283, "accept"),
  SC_ENTRY(284, "connect"),
  SC_ENTRY(285, "bind"),
  SC_ENTRY(286, "listen"),
  SC_ENTRY(287, "setsockopt"),
  SC_ENTRY(288, "getsockopt"),
  SC_ENTRY(289, "socket"),
  SC_ENTRY(290, "socketpair"),
  SC_ENTRY(291, "shutdown"),
  SC_ENTRY(292, "sendto"),
  SC_ENTRY(293, "read"),
  SC_ENTRY(294, "write"),
  SC_ENTRY(295, "close"),
  SC_ENTRY(296, "mmap"),
  SC_ENTRY(297, "munmap"),
  SC_ENTRY(298, "mprotect"),
  SC_ENTRY(299, "madvise"),
  SC_ENTRY(300, "mlock"),
  SC_ENTRY(301, "munlock"),
  SC_ENTRY(302, "mlockall"),
  SC_ENTRY(303, "munlockall"),
  SC_ENTRY(304, "mincore"),
  SC_ENTRY(305, "msync"),
  SC_ENTRY(306, "sigaction"),
  SC_ENTRY(307, "sigprocmask"),
  SC_ENTRY(308, "sigpending"),
  SC_ENTRY(309, "sigreturn"),
  SC_ENTRY(310, "sigsuspend"),
  SC_ENTRY(311, "sigaltstack"),
  SC_ENTRY(312, "sched_yield"),
  SC_ENTRY(313, "pause"),
  SC_ENTRY(314, "kill"),
  SC_ENTRY(315, "tkill"),
  SC_ENTRY(316, "tgkill"),
  SC_ENTRY(317, "exit_group"),
  SC_ENTRY(318, "set_tid_address"),
  SC_ENTRY(319, "futex"),
  SC_ENTRY(320, "set_robust_list"),
  SC_ENTRY(321, "get_robust_list"),
  SC_ENTRY(322, "nanosleep"),
  SC_ENTRY(323, "clock_gettime"),
  SC_ENTRY(324, "clock_settime"),
  SC_ENTRY(325, "clock_getres"),
  SC_ENTRY(326, "getitimer"),
  SC_ENTRY(327, "setitimer"),
  SC_ENTRY(328, "timer_create"),
  SC_ENTRY(329, "timer_delete"),
  SC_ENTRY(330, "timer_settime"),
  SC_ENTRY(331, "timer_gettime"),
  SC_ENTRY(332, "timer_getoverrun"),
  SC_ENTRY(333, "getpid"),
  SC_ENTRY(334, "getppid"),
  SC_ENTRY(335, "getuid"),
  SC_ENTRY(336, "geteuid"),
  SC_ENTRY(337, "getgid"),
  SC_ENTRY(338, "getegid"),
  SC_ENTRY(339, "getgroups"),
  SC_ENTRY(340, "setgroups"),
  SC_ENTRY(341, "setuid"),
  SC_ENTRY(342, "setgid"),
  SC_ENTRY(343, "seteuid"),
  SC_ENTRY(344, "setegid"),
  SC_ENTRY(345, "setreuid"),
  SC_ENTRY(346, "setregid"),
  SC_ENTRY(347, "getresuid"),
  SC_ENTRY(348, "getresgid"),
  SC_ENTRY(349, "setresuid"),
  SC_ENTRY(350, "setresgid"),
  SC_ENTRY(351, "getsid"),
  SC_ENTRY(352, "setsid"),
  SC_ENTRY(353, "getpgid"),
  SC_ENTRY(354, "setpgid"),
  SC_ENTRY(355, "getpgrp"),
  SC_ENTRY(356, "getpriority"),
  SC_ENTRY(357, "setpriority"),
  SC_ENTRY(358, "getrusage"),
  SC_ENTRY(359, "getrlimit"),
  SC_ENTRY(360, "setrlimit"),
  SC_ENTRY(361, "getcwd"),
  SC_ENTRY(362, "umask"),
  SC_ENTRY(363, "chdir"),
  SC_ENTRY(364, "fchdir"),
  SC_ENTRY(365, "chroot"),
  SC_ENTRY(366, "pivot_root"),
  SC_ENTRY(367, "acct"),
  SC_ENTRY(368, "sync"),
  SC_ENTRY(369, "fsync"),
  SC_ENTRY(370, "fdatasync"),
  SC_ENTRY(371, "swapon"),
  SC_ENTRY(372, "swapoff"),
  SC_ENTRY(373, "quotactl"),
  SC_ENTRY(374, "sysfs"),
  SC_ENTRY(375, "uname"),
  SC_ENTRY(376, "sched_setscheduler"),
  SC_ENTRY(377, "sched_getscheduler"),
  SC_ENTRY(378, "sched_getparam"),
  SC_ENTRY(379, "sched_setparam"),
  SC_ENTRY(380, "sched_get_priority_max"),
  SC_ENTRY(381, "sched_get_priority_min"),
  SC_ENTRY(382, "sched_rr_get_interval"),
  SC_ENTRY(383, "iopl"),
  SC_ENTRY(384, "ioperm"),
  SC_ENTRY(385, "syslog"),
  SC_ENTRY(386, "vhangup"),
  SC_ENTRY(387, "personality"),
  SC_ENTRY(388, "prctl"),
  SC_ENTRY(389, "arch_prctl"),
  SC_ENTRY(390, "adjtimex"),
  SC_ENTRY(391, "set_tls"),
  SC_ENTRY(392, "reboot"),
  SC_ENTRY(393, "stime"),
  SC_ENTRY(394, "capget"),
  SC_ENTRY(395, "capset"),
  SC_ENTRY(396, "sysinfo"),
  SC_ENTRY(397, "modprobe"),
  SC_ENTRY(398, "nfs_clnt"),
  SC_ENTRY(399, "nfssvc"),
  SC_ENTRY(400, "pciconf_read"),
  SC_ENTRY(401, "pciconf_write"),
  SC_ENTRY(402, "pciconf_open"),
  SC_ENTRY(403, "pciconf_close"),
  SC_ENTRY(404, "open"),
  SC_ENTRY(405, "close"),
  SC_ENTRY(406, "read"),
  SC_ENTRY(407, "write"),
  SC_ENTRY(408, "ioctl"),
  SC_ENTRY(409, "select"),
  SC_ENTRY(410, "poll"),
  SC_ENTRY(411, "epoll_create"),
  SC_ENTRY(412, "epoll_ctl"),
  SC_ENTRY(413, "epoll_wait"),
  SC_ENTRY(414, "eventfd"),
  SC_ENTRY(415, "signalfd"),
  SC_ENTRY(416, "timerfd_create"),
  SC_ENTRY(417, "timerfd_settime"),
  SC_ENTRY(418, "timerfd_gettime"),
  SC_ENTRY(419, "inotify_init"),
  SC_ENTRY(420, "inotify_add_watch"),
  SC_ENTRY(421, "inotify_rm_watch"),
  SC_ENTRY(422, "sem_open"),
  SC_ENTRY(423, "sem_close"),
  SC_ENTRY(424, "sem_unlink"),
  SC_ENTRY(425, "sem_wait"),
  SC_ENTRY(426, "sem_trywait"),
  SC_ENTRY(427, "sem_timedwait"),
  SC_ENTRY(428, "sem_post"),
  SC_ENTRY(429, "sem_getvalue"),
  SC_ENTRY(430, "shm_open"),
  SC_ENTRY(431, "shm_unlink"),
  SC_ENTRY(432, "shmget"),
  SC_ENTRY(433, "shmctl"),
  SC_ENTRY(434, "shmat"),
  SC_ENTRY(435, "shmdt"),
  SC_ENTRY(436, "msgget"),
  SC_ENTRY(437, "msgsnd"),
  SC_ENTRY(438, "msgrcv"),
  SC_ENTRY(439, "msgctl"),
  SC_ENTRY(440, "flock"),
  SC_ENTRY(441, "lockf"),
  SC_ENTRY(442, "posix_fadvise"),
  SC_ENTRY(443, "posix_fallocate"),
  SC_ENTRY(444, "fallocate"),
  SC_ENTRY(445, "ftruncate"),
  SC_ENTRY(446, "truncate"),
  SC_ENTRY(447, "lseek"),
  SC_ENTRY(448, "tell"),
  SC_ENTRY(449, "fcntl"),
  SC_ENTRY(450, "dup"),
  SC_ENTRY(451, "dup2"),
  SC_ENTRY(452, "dup3"),
  SC_ENTRY(453, "close_range"),
  SC_ENTRY(454, "mkfifo"),
  SC_ENTRY(455, "pipe"),
  SC_ENTRY(456, "pipe2"),
  SC_ENTRY(457, "socket"),
  SC_ENTRY(458, "socketpair"),
  SC_ENTRY(459, "bind"),
  SC_ENTRY(460, "listen"),
  SC_ENTRY(461, "accept"),
  SC_ENTRY(462, "accept4"),
  SC_ENTRY(463, "connect"),
  SC_ENTRY(464, "shutdown"),
  SC_ENTRY(465, "sendmsg"),
  SC_ENTRY(466, "recvmsg"),
  SC_ENTRY(467, "sendto"),
  SC_ENTRY(468, "recvfrom"),
  SC_ENTRY(469, "setsockopt"),
  SC_ENTRY(470, "getsockopt"),
  SC_ENTRY(471, "getpeername"),
  SC_ENTRY(472, "getsockname"),
  SC_ENTRY(473, "sched_yield"),
  SC_ENTRY(474, "sched_getparam"),
  SC_ENTRY(475, "sched_setparam"),
  SC_ENTRY(476, "sched_getscheduler"),
  SC_ENTRY(477, "sched_setscheduler"),
  SC_ENTRY(478, "sched_get_priority_max"),
  SC_ENTRY(479, "sched_get_priority_min"),
  SC_ENTRY(480, "sched_rr_get_interval"),
  SC_ENTRY(481, "sched_setaffinity"),
  SC_ENTRY(482, "sched_getaffinity"),
  SC_ENTRY(483, "futex"),
  SC_ENTRY(484, "futex_requeue"),
  SC_ENTRY(485, "futex_wait"),
  SC_ENTRY(486, "futex_wake"),
  SC_ENTRY(487, "set_robust_list"),
  SC_ENTRY(488, "get_robust_list"),
  SC_ENTRY(489, "getcpu"),
  SC_ENTRY(490, "set_tid_address"),
  SC_ENTRY(491, "get_thread_area"),
  SC_ENTRY(492, "set_thread_area"),
  SC_ENTRY(493, "exit_group"),
  SC_ENTRY(494, "tkill"),
  SC_ENTRY(495, "tgkill"),
  SC_ENTRY(496, "rt_sigaction"),
  SC_ENTRY(497, "rt_sigprocmask"),
  SC_ENTRY(498, "rt_sigpending"),
  SC_ENTRY(499, "rt_sigreturn"),
  SC_ENTRY(500, "rt_sigsuspend"),
  SC_ENTRY(501, "rt_sigtimedwait"),
  SC_ENTRY(502, "rt_sigqueueinfo"),
  SC_ENTRY(503, "restart_syscall"),
  SC_ENTRY(504, "sigwaitinfo"),
  SC_ENTRY(505, "ioprio_get"),
  SC_ENTRY(506, "ioprio_set"),
  SC_ENTRY(507, "move_pages"),
  SC_ENTRY(508, "mbind"),
  SC_ENTRY(509, "set_mempolicy"),
  SC_ENTRY(510, "get_mempolicy"),
  SC_ENTRY(511, "migrate_pages"),
  SC_ENTRY(512, "name_to_handle_at"),
  SC_ENTRY(513, "open_by_handle_at"),
  SC_ENTRY(514, "clock_adjtime"),
  SC_ENTRY(515, "syncfs"),
  SC_ENTRY(516, "setns"),
  SC_ENTRY(517, "unshare"),
  SC_ENTRY(518, "getrandom"),
  SC_ENTRY(519, "memfd_create"),
  SC_ENTRY(520, "kcmp"),
  SC_ENTRY(521, "explicit_bzero"),
  SC_ENTRY(522, "pselect6"),
  SC_ENTRY(523, "ppoll"),
  SC_ENTRY(524, "sched_getattr"),
  SC_ENTRY(525, "sched_setattr"),
};

static const int sc_table_count =
    (int)(sizeof(sc_table) / sizeof(sc_table[0]));

const char *memdbg_tracer_syscall_name(int syscall_no) {
  int lo = 0;
  int hi = sc_table_count - 1;
  while (lo <= hi) {
    int mid = lo + (hi - lo) / 2;
    if (sc_table[mid].no < syscall_no)
      lo = mid + 1;
    else if (sc_table[mid].no > syscall_no)
      hi = mid - 1;
    else
      return sc_table[mid].name;
  }
  return "unknown";
}

/* ------------------------------------------------------------------ */
/*  macOS (x86-64 / arm64) syscall table                              */
/* ------------------------------------------------------------------ */

#elif defined(__APPLE__)

#define SC_ENTRY(n, s) { n, s }

static const struct { int no; const char *name; } sc_table[] = {
  SC_ENTRY(  0, "syscall"),
  SC_ENTRY(  1, "exit"),
  SC_ENTRY(  2, "fork"),
  SC_ENTRY(  3, "read"),
  SC_ENTRY(  4, "write"),
  SC_ENTRY(  5, "open"),
  SC_ENTRY(  6, "close"),
  SC_ENTRY(  7, "wait4"),
  SC_ENTRY(  8, "link"),
  SC_ENTRY(  9, "unlink"),
  SC_ENTRY( 10, "execve"),
  SC_ENTRY( 11, "chdir"),
  SC_ENTRY( 12, "fchdir"),
  SC_ENTRY( 13, "mknod"),
  SC_ENTRY( 14, "chmod"),
  SC_ENTRY( 15, "chown"),
  SC_ENTRY( 16, "getfsstat"),
  SC_ENTRY( 17, "setuid_ia"),
  SC_ENTRY( 18, "getpid"),
  SC_ENTRY( 19, "setuid_ic"),
  SC_ENTRY( 20, "getpid"),
  SC_ENTRY( 21, "setuid"),
  SC_ENTRY( 22, "getuid"),
  SC_ENTRY( 23, "geteuid"),
  SC_ENTRY( 24, "ptrace"),
  SC_ENTRY( 25, "recvmsg"),
  SC_ENTRY( 26, "sendmsg"),
  SC_ENTRY( 27, "recvfrom"),
  SC_ENTRY( 28, "accept"),
  SC_ENTRY( 29, "getpeername"),
  SC_ENTRY( 30, "getsockname"),
  SC_ENTRY( 31, "access"),
  SC_ENTRY( 32, "chflags"),
  SC_ENTRY( 33, "fchflags"),
  SC_ENTRY( 34, "sync"),
  SC_ENTRY( 35, "kill"),
  SC_ENTRY( 36, "getppid"),
  SC_ENTRY( 37, "dup"),
  SC_ENTRY( 38, "pipe"),
  SC_ENTRY( 39, "getegid"),
  SC_ENTRY( 40, "sigaction"),
  SC_ENTRY( 41, "getgid"),
  SC_ENTRY( 42, "sigprocmask"),
  SC_ENTRY( 43, "getlogin"),
  SC_ENTRY( 44, "setlogin"),
  SC_ENTRY( 45, "acct"),
  SC_ENTRY( 46, "sigpending"),
  SC_ENTRY( 47, "sigaltstack"),
  SC_ENTRY( 48, "ioctl"),
  SC_ENTRY( 49, "reboot"),
  SC_ENTRY( 50, "revoke"),
  SC_ENTRY( 51, "symlink"),
  SC_ENTRY( 52, "readlink"),
  SC_ENTRY( 53, "execve"),
  SC_ENTRY( 54, "umask"),
  SC_ENTRY( 55, "chroot"),
  SC_ENTRY( 56, "msync"),
  SC_ENTRY( 57, "vfork"),
  SC_ENTRY( 60, "munmap"),
  SC_ENTRY( 61, "mprotect"),
  SC_ENTRY( 62, "madvise"),
  SC_ENTRY( 63, "invalid"),
  SC_ENTRY( 64, "mincore"),
  SC_ENTRY( 65, "getgroups"),
  SC_ENTRY( 66, "setgroups"),
  SC_ENTRY( 67, "getpgrp"),
  SC_ENTRY( 68, "setpgid"),
  SC_ENTRY( 69, "setitimer"),
  SC_ENTRY( 70, "swapon"),
  SC_ENTRY( 71, "getitimer"),
  SC_ENTRY( 72, "getdtablesize"),
  SC_ENTRY( 73, "dup2"),
  SC_ENTRY( 74, "fcntl"),
  SC_ENTRY( 75, "select"),
  SC_ENTRY( 76, "fsync"),
  SC_ENTRY( 77, "setpriority"),
  SC_ENTRY( 78, "socket"),
  SC_ENTRY( 79, "connect"),
  SC_ENTRY( 80, "getpriority"),
  SC_ENTRY( 81, "bind"),
  SC_ENTRY( 82, "setsockopt"),
  SC_ENTRY( 83, "listen"),
  SC_ENTRY( 84, "sigsuspend"),
  SC_ENTRY( 85, "gettimeofday"),
  SC_ENTRY( 86, "getrusage"),
  SC_ENTRY( 87, "getsockopt"),
  SC_ENTRY( 88, "readv"),
  SC_ENTRY( 89, "writev"),
  SC_ENTRY( 90, "settimeofday"),
  SC_ENTRY( 91, "fchown"),
  SC_ENTRY( 92, "fchmod"),
  SC_ENTRY( 93, "setreuid"),
  SC_ENTRY( 94, "setregid"),
  SC_ENTRY( 95, "rename"),
  SC_ENTRY( 96, "flock"),
  SC_ENTRY( 97, "mkfifo"),
  SC_ENTRY( 98, "sendto"),
  SC_ENTRY( 99, "shutdown"),
  SC_ENTRY(100, "socketpair"),
  SC_ENTRY(101, "mkdir"),
  SC_ENTRY(102, "rmdir"),
  SC_ENTRY(103, "utimes"),
  SC_ENTRY(104, "adjtime"),
  SC_ENTRY(105, "setsid"),
  SC_ENTRY(106, "getpgid"),
  SC_ENTRY(107, "setprivexec"),
  SC_ENTRY(108, "pread"),
  SC_ENTRY(109, "pwrite"),
  SC_ENTRY(110, "nfssvc"),
  SC_ENTRY(111, "statfs"),
  SC_ENTRY(112, "fstatfs"),
  SC_ENTRY(113, "unmount"),
  SC_ENTRY(114, "async_daemon"),
  SC_ENTRY(115, "getfh"),
  SC_ENTRY(116, "quotactl"),
  SC_ENTRY(117, "mount"),
  SC_ENTRY(118, "csops"),
  SC_ENTRY(119, "csops_audittoken"),
  SC_ENTRY(120, "waitid"),
  SC_ENTRY(121, "kdebug_typefilter"),
  SC_ENTRY(122, "kdebug_trace_string"),
  SC_ENTRY(123, "kdebug_trace64"),
  SC_ENTRY(124, "kdebug_trace"),
  SC_ENTRY(125, "setgid"),
  SC_ENTRY(126, "setegid"),
  SC_ENTRY(127, "seteuid"),
  SC_ENTRY(128, "sigreturn"),
  SC_ENTRY(129, "fdatasync"),
  SC_ENTRY(130, "stat"),
  SC_ENTRY(131, "fstat"),
  SC_ENTRY(132, "lstat"),
  SC_ENTRY(133, "pathconf"),
  SC_ENTRY(134, "fpathconf"),
  SC_ENTRY(135, "getrlimit"),
  SC_ENTRY(136, "setrlimit"),
  SC_ENTRY(137, "getdirentries"),
  SC_ENTRY(138, "mmap"),
  SC_ENTRY(139, "__syscall"),
  SC_ENTRY(140, "lseek"),
  SC_ENTRY(141, "truncate"),
  SC_ENTRY(142, "ftruncate"),
  SC_ENTRY(143, "sysctl"),
  SC_ENTRY(144, "mlock"),
  SC_ENTRY(145, "munlock"),
  SC_ENTRY(146, "undelete"),
  SC_ENTRY(147, "open_dprotected_np"),
  SC_ENTRY(148, "fsgetpath_ext"),
  SC_ENTRY(149, "openat_dprotected_np"),
  SC_ENTRY(150, "getattrlist"),
  SC_ENTRY(151, "setattrlist"),
  SC_ENTRY(152, "getdirentriesattr"),
  SC_ENTRY(153, "exchangedata"),
  SC_ENTRY(154, "searchfs"),
  SC_ENTRY(155, "delete"),
  SC_ENTRY(156, "copyfile"),
  SC_ENTRY(157, "fgetattrlist"),
  SC_ENTRY(158, "fsetattrlist"),
  SC_ENTRY(159, "poll"),
  SC_ENTRY(160, "getxattr"),
  SC_ENTRY(161, "fgetxattr"),
  SC_ENTRY(162, "setxattr"),
  SC_ENTRY(163, "fsetxattr"),
  SC_ENTRY(164, "removexattr"),
  SC_ENTRY(165, "fremovexattr"),
  SC_ENTRY(166, "listxattr"),
  SC_ENTRY(167, "flistxattr"),
  SC_ENTRY(168, "fsctl"),
  SC_ENTRY(169, "initgroups"),
  SC_ENTRY(170, "posix_spawn"),
  SC_ENTRY(171, "ffsctl"),
  SC_ENTRY(172, "fhopen"),
  SC_ENTRY(173, "minherit"),
  SC_ENTRY(174, "semsys"),
  SC_ENTRY(175, "msgsys"),
  SC_ENTRY(176, "shmsys"),
  SC_ENTRY(177, "semctl"),
  SC_ENTRY(178, "semget"),
  SC_ENTRY(179, "semop"),
  SC_ENTRY(180, "msgctl"),
  SC_ENTRY(181, "msgget"),
  SC_ENTRY(182, "msgsnd"),
  SC_ENTRY(183, "msgrcv"),
  SC_ENTRY(184, "shmat"),
  SC_ENTRY(185, "shmctl"),
  SC_ENTRY(186, "shmdt"),
  SC_ENTRY(187, "shmget"),
  SC_ENTRY(188, "shm_open"),
  SC_ENTRY(189, "shm_unlink"),
  SC_ENTRY(190, "sem_open"),
  SC_ENTRY(191, "sem_close"),
  SC_ENTRY(192, "sem_unlink"),
  SC_ENTRY(193, "sem_wait"),
  SC_ENTRY(194, "sem_trywait"),
  SC_ENTRY(195, "sem_post"),
  SC_ENTRY(196, "sysctlbyname"),
  SC_ENTRY(197, "open_extended"),
  SC_ENTRY(198, "umask_extended"),
  SC_ENTRY(199, "stat_extended"),
  SC_ENTRY(200, "lstat_extended"),
  SC_ENTRY(201, "fstat_extended"),
  SC_ENTRY(202, "chmod_extended"),
  SC_ENTRY(203, "fchmod_extended"),
  SC_ENTRY(204, "access_extended"),
  SC_ENTRY(205, "settid"),
  SC_ENTRY(206, "gettid"),
  SC_ENTRY(207, "setsgroups"),
  SC_ENTRY(208, "getsgroups"),
  SC_ENTRY(209, "setwgroups"),
  SC_ENTRY(210, "getwgroups"),
  SC_ENTRY(211, "mkfifo_extended"),
  SC_ENTRY(212, "mkdir_extended"),
  SC_ENTRY(213, "identitysvc"),
  SC_ENTRY(214, "shared_region_check_np"),
  SC_ENTRY(215, "vm_pressure_monitor"),
  SC_ENTRY(216, "psynch_rw_longrdlock"),
  SC_ENTRY(217, "psynch_rw_yieldwrlock"),
  SC_ENTRY(218, "psynch_rw_downgrade"),
  SC_ENTRY(219, "psynch_rw_upgrade"),
  SC_ENTRY(220, "psynch_mutexwait"),
  SC_ENTRY(221, "psynch_mutexdrop"),
  SC_ENTRY(222, "psynch_cvbroad"),
  SC_ENTRY(223, "psynch_cvsignal"),
  SC_ENTRY(224, "psynch_cvwait"),
  SC_ENTRY(225, "psynch_rw_rdlock"),
  SC_ENTRY(226, "psynch_rw_wrlock"),
  SC_ENTRY(227, "psynch_rw_unlock"),
  SC_ENTRY(228, "psynch_rw_unlock2"),
  SC_ENTRY(229, "getsid"),
  SC_ENTRY(230, "settid_with_pid"),
  SC_ENTRY(231, "psynch_cvclrprepost"),
  SC_ENTRY(232, "aio_fsync"),
  SC_ENTRY(233, "aio_return"),
  SC_ENTRY(234, "aio_suspend"),
  SC_ENTRY(235, "aio_cancel"),
  SC_ENTRY(236, "aio_error"),
  SC_ENTRY(237, "aio_read"),
  SC_ENTRY(238, "aio_write"),
  SC_ENTRY(239, "lio_listio"),
  SC_ENTRY(240, "iopolicysys"),
  SC_ENTRY(241, "process_policy"),
  SC_ENTRY(242, "mlockall"),
  SC_ENTRY(243, "munlockall"),
  SC_ENTRY(244, "issetugid"),
  SC_ENTRY(245, "__pthread_kill"),
  SC_ENTRY(246, "__pthread_sigmask"),
  SC_ENTRY(247, "__sigwait"),
  SC_ENTRY(248, "__disable_threadsignal"),
  SC_ENTRY(249, "__pthread_markcancel"),
  SC_ENTRY(250, "__pthread_canceled"),
  SC_ENTRY(251, "__semwait_signal"),
  SC_ENTRY(252, "proc_info"),
  SC_ENTRY(253, "sendfile"),
  SC_ENTRY(254, "stat64"),
  SC_ENTRY(255, "fstat64"),
  SC_ENTRY(256, "lstat64"),
  SC_ENTRY(257, "stat64_extended"),
  SC_ENTRY(258, "lstat64_extended"),
  SC_ENTRY(259, "fstat64_extended"),
  SC_ENTRY(260, "getdirentries64"),
  SC_ENTRY(261, "statfs64"),
  SC_ENTRY(262, "fstatfs64"),
  SC_ENTRY(263, "getfsstat64"),
  SC_ENTRY(264, "__pthread_chdir"),
  SC_ENTRY(265, "__pthread_fchdir"),
  SC_ENTRY(266, "audit"),
  SC_ENTRY(267, "auditon"),
  SC_ENTRY(268, "getauid"),
  SC_ENTRY(269, "setauid"),
  SC_ENTRY(270, "getaudit_addr"),
  SC_ENTRY(271, "setaudit_addr"),
  SC_ENTRY(272, "auditctl"),
  SC_ENTRY(273, "bsdthread_create"),
  SC_ENTRY(274, "bsdthread_terminate"),
  SC_ENTRY(275, "kqueue"),
  SC_ENTRY(276, "kevent"),
  SC_ENTRY(277, "lchown"),
  SC_ENTRY(278, "bsdthread_register"),
  SC_ENTRY(279, "workq_open"),
  SC_ENTRY(280, "workq_kernreturn"),
  SC_ENTRY(281, "kevent64"),
  SC_ENTRY(282, "thread_selfid"),
  SC_ENTRY(283, "ledger"),
  SC_ENTRY(284, "kevent_qos"),
  SC_ENTRY(285, "kevent_id"),
  SC_ENTRY(286, "__mac_execve"),
  SC_ENTRY(287, "__mac_syscall"),
  SC_ENTRY(288, "__mac_get_file"),
  SC_ENTRY(289, "__mac_set_file"),
  SC_ENTRY(290, "__mac_get_link"),
  SC_ENTRY(291, "__mac_set_link"),
  SC_ENTRY(292, "__mac_get_proc"),
  SC_ENTRY(293, "__mac_set_proc"),
  SC_ENTRY(294, "__mac_get_fd"),
  SC_ENTRY(295, "__mac_set_fd"),
  SC_ENTRY(296, "__mac_get_pid"),
  SC_ENTRY(297, "pselect"),
  SC_ENTRY(298, "pselect_nocancel"),
  SC_ENTRY(299, "read_nocancel"),
  SC_ENTRY(300, "write_nocancel"),
  SC_ENTRY(301, "open_nocancel"),
  SC_ENTRY(302, "close_nocancel"),
  SC_ENTRY(303, "wait4_nocancel"),
  SC_ENTRY(304, "recvmsg_nocancel"),
  SC_ENTRY(305, "sendmsg_nocancel"),
  SC_ENTRY(306, "recvfrom_nocancel"),
  SC_ENTRY(307, "accept_nocancel"),
  SC_ENTRY(308, "msync_nocancel"),
  SC_ENTRY(309, "fcntl_nocancel"),
  SC_ENTRY(310, "select_nocancel"),
  SC_ENTRY(311, "fsync_nocancel"),
  SC_ENTRY(312, "connect_nocancel"),
  SC_ENTRY(313, "sigsuspend_nocancel"),
  SC_ENTRY(314, "readv_nocancel"),
  SC_ENTRY(315, "writev_nocancel"),
  SC_ENTRY(316, "sendto_nocancel"),
  SC_ENTRY(317, "pread_nocancel"),
  SC_ENTRY(318, "pwrite_nocancel"),
  SC_ENTRY(319, "waitid_nocancel"),
  SC_ENTRY(320, "poll_nocancel"),
  SC_ENTRY(321, "msgsnd_nocancel"),
  SC_ENTRY(322, "msgrcv_nocancel"),
  SC_ENTRY(323, "sem_wait_nocancel"),
  SC_ENTRY(324, "aio_suspend_nocancel"),
  SC_ENTRY(325, "__sigwait_nocancel"),
  SC_ENTRY(326, "__semwait_signal_nocancel"),
  SC_ENTRY(327, "__mac_mount"),
  SC_ENTRY(328, "__mac_get_mount"),
  SC_ENTRY(329, "__mac_getfsstat"),
  SC_ENTRY(330, "fsgetpath"),
  SC_ENTRY(331, "audit_session_self"),
  SC_ENTRY(332, "audit_session_join"),
  SC_ENTRY(333, "fileport_makeport"),
  SC_ENTRY(334, "fileport_makefd"),
  SC_ENTRY(335, "audit_session_port"),
  SC_ENTRY(336, "pid_suspend"),
  SC_ENTRY(337, "pid_resume"),
  SC_ENTRY(338, "pid_hibernate"),
  SC_ENTRY(339, "pid_shutdown_sockets"),
  SC_ENTRY(340, "kas_info"),
  SC_ENTRY(341, "memorystatus_control"),
  SC_ENTRY(342, "guarded_open_np"),
  SC_ENTRY(343, "guarded_close_np"),
  SC_ENTRY(344, "guarded_kqueue_np"),
  SC_ENTRY(345, "change_fdguard_np"),
  SC_ENTRY(346, "usrctl"),
  SC_ENTRY(347, "proc_rlimit_control"),
  SC_ENTRY(348, "connectx"),
  SC_ENTRY(349, "disconnectx"),
  SC_ENTRY(350, "peeloff"),
  SC_ENTRY(351, "socket_delegate"),
  SC_ENTRY(352, "telemetry"),
  SC_ENTRY(353, "proc_uuid_policy"),
  SC_ENTRY(354, "memorystatus_get_level"),
  SC_ENTRY(355, "system_override"),
  SC_ENTRY(356, "vfs_purge"),
  SC_ENTRY(357, "sfi_ctl"),
  SC_ENTRY(358, "sfi_pidctl"),
  SC_ENTRY(359, "coalition"),
  SC_ENTRY(360, "coalition_info"),
  SC_ENTRY(361, "necp_match_policy"),
  SC_ENTRY(362, "getattrlistbulk"),
  SC_ENTRY(363, "clonefileat"),
  SC_ENTRY(364, "openat"),
  SC_ENTRY(365, "openat_nocancel"),
  SC_ENTRY(366, "renameat"),
  SC_ENTRY(367, "faccessat"),
  SC_ENTRY(368, "fchmodat"),
  SC_ENTRY(369, "fchownat"),
  SC_ENTRY(370, "fstatat"),
  SC_ENTRY(371, "fstatat64"),
  SC_ENTRY(372, "linkat"),
  SC_ENTRY(373, "unlinkat"),
  SC_ENTRY(374, "readlinkat"),
  SC_ENTRY(375, "symlinkat"),
  SC_ENTRY(376, "mkdirat"),
  SC_ENTRY(377, "getattrlistat"),
  SC_ENTRY(378, "proc_trace_log"),
  SC_ENTRY(379, "bsdthread_ctl"),
  SC_ENTRY(380, "openbyid_np"),
  SC_ENTRY(381, "recvmsg_x"),
  SC_ENTRY(382, "sendmsg_x"),
  SC_ENTRY(383, "thread_selfusage"),
  SC_ENTRY(384, "csrctl"),
  SC_ENTRY(385, "guarded_open_dprotected_np"),
  SC_ENTRY(386, "guarded_write_np"),
  SC_ENTRY(387, "guarded_pwrite_np"),
  SC_ENTRY(388, "guarded_writev_np"),
  SC_ENTRY(389, "renameatx_np"),
  SC_ENTRY(390, "mremap_encrypted"),
  SC_ENTRY(391, "netagent_trigger"),
  SC_ENTRY(392, "stack_snapshot_with_config"),
  SC_ENTRY(393, "microstackshot"),
  SC_ENTRY(394, "grab_pgo_data"),
  SC_ENTRY(395, "persona"),
  SC_ENTRY(396, "mach_eventlink_signal"),
  SC_ENTRY(397, "mach_eventlink_wait_until"),
  SC_ENTRY(398, "mach_eventlink_signal_wait_until"),
  SC_ENTRY(399, "work_interval_ctl"),
  SC_ENTRY(400, "getentropy"),
  SC_ENTRY(401, "necp_open"),
  SC_ENTRY(402, "necp_client_action"),
  SC_ENTRY(403, "__nexus_open"),
  SC_ENTRY(404, "__nexus_register"),
  SC_ENTRY(405, "__nexus_deregister"),
  SC_ENTRY(406, "__nexus_create"),
  SC_ENTRY(407, "__nexus_destroy"),
  SC_ENTRY(408, "__nexus_get_opt"),
  SC_ENTRY(409, "__nexus_set_opt"),
  SC_ENTRY(410, "__channel_open"),
  SC_ENTRY(411, "__channel_get_info"),
  SC_ENTRY(412, "__channel_sync"),
  SC_ENTRY(413, "__channel_get_opt"),
  SC_ENTRY(414, "__channel_set_opt"),
  SC_ENTRY(415, "ulock_wait"),
  SC_ENTRY(416, "ulock_wake"),
  SC_ENTRY(417, "fclonefileat"),
  SC_ENTRY(418, "fs_snapshot"),
  SC_ENTRY(419, "register_uexc_handler"),
  SC_ENTRY(420, "terminate_with_payload"),
  SC_ENTRY(421, "abort_with_payload"),
  SC_ENTRY(422, "necp_session_open"),
  SC_ENTRY(423, "necp_session_action"),
  SC_ENTRY(424, "setattrlistat"),
  SC_ENTRY(425, "net_qos_guideline"),
  SC_ENTRY(426, "fmount"),
  SC_ENTRY(427, "ntp_adjtime"),
  SC_ENTRY(428, "ntp_gettime"),
  SC_ENTRY(429, "os_fault_with_payload"),
  SC_ENTRY(430, "kqueue_workloop_ctl"),
  SC_ENTRY(431, "__mach_bridge_remote_time"),
  SC_ENTRY(432, "coalition_ledger"),
  SC_ENTRY(433, "log_data"),
  SC_ENTRY(434, "memorystatus_available_memory"),
  SC_ENTRY(435, "objc_bp_assist_cfg_np"),
  SC_ENTRY(436, "shared_region_map_and_slide_2_np"),
  SC_ENTRY(437, "pivot_root"),
  SC_ENTRY(438, "task_inspect_for_pid"),
  SC_ENTRY(439, "task_read_for_pid"),
  SC_ENTRY(440, "preadv"),
  SC_ENTRY(441, "pwritev"),
  SC_ENTRY(442, "preadv_nocancel"),
  SC_ENTRY(443, "pwritev_nocancel"),
  SC_ENTRY(444, "ulock_wait2"),
  SC_ENTRY(445, "proc_info_extended_id"),
  SC_ENTRY(446, "tracker_action"),
  SC_ENTRY(447, "debug_syscall_reject"),
  SC_ENTRY(448, "debug_syscall_reject_config"),
  SC_ENTRY(449, "graftdmg"),
  SC_ENTRY(450, "map_with_linking_np"),
  SC_ENTRY(451, "freadlink"),
  SC_ENTRY(452, "record_system_event"),
  SC_ENTRY(453, "mkfifoat"),
  SC_ENTRY(454, "mknodat"),
  SC_ENTRY(455, "ungraftdmg"),
  SC_ENTRY(456, "coalition_policy_set"),
  SC_ENTRY(457, "coalition_policy_get"),
};

static const int sc_table_count =
    (int)(sizeof(sc_table) / sizeof(sc_table[0]));

const char *memdbg_tracer_syscall_name(int syscall_no) {
  int lo = 0;
  int hi = sc_table_count - 1;
  while (lo <= hi) {
    int mid = lo + (hi - lo) / 2;
    if (sc_table[mid].no < syscall_no)
      lo = mid + 1;
    else if (sc_table[mid].no > syscall_no)
      hi = mid - 1;
    else
      return sc_table[mid].name;
  }
  return "unknown";
}

/* ------------------------------------------------------------------ */
/*  Fallback (should not be reached on a supported platform)          */
/* ------------------------------------------------------------------ */

#else

const char *memdbg_tracer_syscall_name(int syscall_no) {
  (void)syscall_no;
  return "unknown";
}

#endif
