#!/usr/bin/env python3
"""
embed_assets.py — Generate a compilable C++ include from embedded runtime assets.
Only en.json is embedded; other locales are fetched from the repository at
runtime and stored in the per-platform app data directory.

Usage:
  python3 tools/embed_assets.py frontend/locales imgui.ini frontend/src/ui/embedded_assets.inc
"""

import os, sys


def bytes_to_c_array(data: bytes, name: str, indent: int = 0) -> str:
    """Convert raw bytes to a C-style array initializer."""
    prefix = " " * indent
    lines = []
    lines.append(f"{prefix}static const unsigned char {name}[] = {{")
    chunk_size = 16
    for i in range(0, len(data), chunk_size):
        chunk = data[i : i + chunk_size]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + chunk_size < len(data):
            hexes += ","
        lines.append(f"{prefix}    {hexes}")
    lines.append(f"{prefix}}};")
    return "\n".join(lines)


def generate():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <locales_dir> <imgui_ini> <output_file>", file=sys.stderr)
        sys.exit(1)

    locales_dir = sys.argv[1]
    imgui_ini_path = sys.argv[2]
    output_file = sys.argv[3]

    if not os.path.isdir(locales_dir):
        print(f"Locales directory not found: {locales_dir}", file=sys.stderr)
        sys.exit(1)

    locale_files = sorted(
        f for f in os.listdir(locales_dir)
        if f == "en.json" and os.path.isfile(os.path.join(locales_dir, f))
    )

    out_lines = []
    out_lines.append("/*")
    out_lines.append(" * MemDBG - Embedded assets (English locale + imgui.ini).")
    out_lines.append(" * Auto-generated by tools/embed_assets.py - DO NOT EDIT.")
    out_lines.append(" * SPDX-License-Identifier: GPL-3.0-or-later")
    out_lines.append(" */")
    out_lines.append("")
    out_lines.append("#ifndef MEMDBG_FRONTEND_EMBEDDED_ASSETS_INC")
    out_lines.append("#define MEMDBG_FRONTEND_EMBEDDED_ASSETS_INC")
    out_lines.append("")
    out_lines.append('#include <cstddef>')
    out_lines.append('#include <cstdint>')
    out_lines.append("")
    out_lines.append("namespace memdbg::frontend::assets {")
    out_lines.append("")

    # --- Embed locale JSON files ---
    locale_var_names = []
    for filename in locale_files:
        filepath = os.path.join(locales_dir, filename)
        with open(filepath, "rb") as f:
            data = f.read()

        var_name = "kLocale_" + filename.replace(".", "_")
        locale_var_names.append((filename, var_name, len(data)))

        out_lines.append(f"// {filename} ({len(data)} bytes)")
        out_lines.append(bytes_to_c_array(data, var_name, 4))
        out_lines.append(f"static const size_t {var_name}_size = {len(data)};")
        out_lines.append("")

    # --- Embedded locale registry table ---
    out_lines.append("struct EmbeddedLocale {")
    out_lines.append("    const char *filename;")
    out_lines.append("    const unsigned char *data;")
    out_lines.append("    size_t size;")
    out_lines.append("};")
    out_lines.append("")
    out_lines.append(f"static const EmbeddedLocale kEmbeddedLocales[] = {{")
    for filename, var_name, size in locale_var_names:
        out_lines.append(f'    {{"{filename}", {var_name}, {var_name}_size}},')
    out_lines.append("};")
    out_lines.append(f"static const size_t kEmbeddedLocaleCount = {len(locale_var_names)};")
    out_lines.append("")

    # --- Embed imgui.ini ---
    if os.path.isfile(imgui_ini_path):
        with open(imgui_ini_path, "rb") as f:
            ini_data = f.read()
        out_lines.append(f"// imgui.ini ({len(ini_data)} bytes)")
        out_lines.append(bytes_to_c_array(ini_data, "kImGuiIni", 4))
        out_lines.append(f"static const size_t kImGuiIniSize = {len(ini_data)};")
        out_lines.append("")
    else:
        out_lines.append("// imgui.ini not found, embedding empty")
        out_lines.append("static const unsigned char kImGuiIni[] = {};")
        out_lines.append("static const size_t kImGuiIniSize = 0;")
        out_lines.append("")

    out_lines.append("} // namespace memdbg::frontend::assets")
    out_lines.append("")
    out_lines.append("#endif // MEMDBG_FRONTEND_EMBEDDED_ASSETS_INC")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")

    print(f"Generated {output_file} with English locale only", file=sys.stderr)


if __name__ == "__main__":
    generate()
